"""add ondelete

Revision ID: 94d838cdbbaa
Revises: 555d2f0f93fe
Create Date: 2026-02-20 15:37:10.088303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d838cdbbaa'
down_revision: Union[str, Sequence[str], None] = '555d2f0f93fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('category_user_id_fkey'), 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('exercise_category_id_fkey'), 'exercise', type_='foreignkey')
    op.drop_constraint(op.f('exercise_user_id_fkey'), 'exercise', type_='foreignkey')
    op.create_foreign_key(None, 'exercise', 'category', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'exercise', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('set_exercise_id_fkey'), 'set', type_='foreignkey')
    op.drop_constraint(op.f('set_user_id_fkey'), 'set', type_='foreignkey')
    op.create_foreign_key(None, 'set', 'exercise', ['exercise_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'set', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('template_exercise_exercise_id_fkey'), 'template_exercise', type_='foreignkey')
    op.drop_constraint(op.f('template_exercise_workout_template_id_fkey'), 'template_exercise', type_='foreignkey')
    op.create_foreign_key(None, 'template_exercise', 'workout_template', ['workout_template_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'template_exercise', 'exercise', ['exercise_id'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    op.add_column('user', sa.Column('photo_url', sa.String(), nullable=True))
    op.drop_constraint(op.f('workout_template_user_id_fkey'), 'workout_template', type_='foreignkey')
    op.create_foreign_key(None, 'workout_template', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_template', type_='foreignkey')
    op.create_foreign_key(op.f('workout_template_user_id_fkey'), 'workout_template', 'user', ['user_id'], ['id'])
    op.drop_column('user', 'photo_url')
    op.drop_column('user', 'username')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_constraint(None, 'template_exercise', type_='foreignkey')
    op.drop_constraint(None, 'template_exercise', type_='foreignkey')
    op.create_foreign_key(op.f('template_exercise_workout_template_id_fkey'), 'template_exercise', 'workout_template', ['workout_template_id'], ['id'])
    op.create_foreign_key(op.f('template_exercise_exercise_id_fkey'), 'template_exercise', 'exercise', ['exercise_id'], ['id'])
    op.drop_constraint(None, 'set', type_='foreignkey')
    op.drop_constraint(None, 'set', type_='foreignkey')
    op.create_foreign_key(op.f('set_user_id_fkey'), 'set', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('set_exercise_id_fkey'), 'set', 'exercise', ['exercise_id'], ['id'])
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.create_foreign_key(op.f('exercise_user_id_fkey'), 'exercise', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('exercise_category_id_fkey'), 'exercise', 'category', ['category_id'], ['id'])
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key(op.f('category_user_id_fkey'), 'category', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
